name: Build Android
on:
  push:
    branches:
      - working
      - main
      - Fetaures/react-query
      - master
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install yarn dependencies
        run: |
          yarn
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Yarn dependencies
        run: |
          yarn
      - name: Gradle Permissions
        run: |
          cd android && chmod +x ./gradlew
      - name: Clean GradLew
        run: |
          cd android && ./gradlew clean
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease      
      - name: Clear artifacts
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: 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
          expire-in: 2days
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: clean-fold-pickup-release.apk
          path: android/app/build/outputs/apk/release/
