name: Build Android 
on:
  push:
    branches:
      - main
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install yarn dependencies
        run: |
          yarn
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install Yarn dependencies
        run: |
          yarn
      - name: Gradle Permessions
        run: |
         cd android && chmod +x ./gradlew
      - name: Build Android Release
        run: |
         cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: clean-fold-pickup-release.apk
          path: android/app/build/outputs/apk/release/
